[package]
name = "readme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.2.1"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
